[package]
name = "onefmt"
version = "0.1.0"
edition = "2021"

[profile.super-release]
inherits = "release"
opt-level = 3
codegen-units = 1
debug = false
lto = "fat"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive", "string"] }
clap-verbosity-flag = "2.2.1"
env_logger = "0.11.3"
log = "0.4.22"
dirs = "5.0.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
url_serde = "0.2.0"
url = "1.7.2"
urlencoding = "2.1.3"
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls", "http2", "blocking"] }
tokio = { version = "1", features = ["full"] }
wasmtime = "24.0.0"
wasmtime-wasi = "24.0.0"
tempfile = "3.12.0"
minijinja = "2.2.0"
shell-words = "1.1.0"
dialoguer = "0.11.0"
onefmt-plugin-utils = { git = "https://github.com/nahco314/onefmt-plugin-utils", version = "0.1.0" }
nix = { version = "0.29.0", features = ["process", "fs"]}
os_pipe = "1.2.1"
